# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  HUGO_VERSION: 0.49
  GOVER: https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
  GOROOT: /usr/local/go
  GOPATH: ${HOME}

stages:
- stage: "Prepare"
  jobs:
    - job: "Prepare"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - bash: |
          wget ${GOVER}
          tar -xvf go1.12.6.linux-amd64.tar.gz
          mv go /usr/local
          go version
          wget -O hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
          mkdir -p hugobin ~/gopath/bin 
          tar -xzvf hugo.tar.gz -C ./hugobin
          mv ./hugobin/hugo ~/gopath/bin
          hugo.tar.gz && rm -rf ./hugobin
