# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  HUGO_VERSION: 0.49

stages:
- stage: "Prepare"
  jobs:
    - job: "Prepare"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - bash: |
          wget -O hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
          mkdir -p hugobin
          mkdir -p /home/mike
          tar -xzvf hugo.tar.gz -C ./hugobin
          mv ./hugobin/hugo /home/mike/gopath/bin
          hugo.tar.gz && rm -rf ./hugobin
